Реализовано ДЗ-3 myCV
svgnovosibirsk/FocusStartHomeworks pull request #3
Opened 2021-11-13 13:26 UTC by svgnovosibirsk

2021-11-15 07:56 UTC, c0dedbear requested changes
Приложенька прикольная, ну и ты конечно молодец что не боишься что то менять в жизни.

По проекту:
textView - можно редактировать, вопрос зачем?  xD
На SE на втором экране довольно резкая граница между текстом и кнопками. Я бы убрал их пониже.

2021-11-15 07:56 UTC, c0dedbear commented on Homework3/myCV/myCV/Controller/MainInfoViewController.swift
> +class MainInfoViewController: UIViewController {
final

2021-11-15 07:56 UTC, c0dedbear commented on Homework3/myCV/myCV/Controller/MainInfoViewController.swift
> +extension MainInfoViewController {
можно сделать private extension и тогда все методы и свойства внутри станут private

2021-11-15 07:56 UTC, c0dedbear commented on Homework3/myCV/myCV/Model/UserProfile.swift
> +class UserProfile {
Чем обоснуешь использование класса вместо структуры?

2021-11-15 07:56 UTC, c0dedbear commented on Homework3/myCV/myCV/SceneDelegate.swift
> +private extension SceneDelegate {
вообще такие штуки настраивают не здесь, зря этот код скопировал из hitTest ). 
По хорошему должна быть фабрика которая собирает модуль, а так ты получается даешь SceneDelegate отвественность, которая не нужна ему. Первая буква из SOLID.   Но думаю, после занятий по архитектуре поймешь этот коммент)

2021-11-16 04:31 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Controller/MainInfoViewController.swift
> +class MainInfoViewController: UIViewController {
Исправлено

2021-11-16 04:31 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Controller/MainInfoViewController.swift
> +extension MainInfoViewController {
Исправлено

2021-11-16 04:31 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Model/UserProfile.swift
> +class UserProfile {
Исправлено

2021-11-16 04:31 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/SceneDelegate.swift
> +private extension SceneDelegate {
Исправлено

2021-11-16 06:12 UTC, c0dedbear requested changes
Поправить модификаторы доступа и см. комментарии.

2021-11-16 06:12 UTC, c0dedbear commented on Homework3/myCV/myCV/Utilites/TabBarControllerGenerator.swift
> +    static let instance = TabBarControllerGenerator()
зачем классу хранить свой экземпляр у себя в статике?

2021-11-16 06:12 UTC, c0dedbear commented on Homework3/myCV/myCV/Model/UserProfile.swift
> +    //static let instance = UserProfile()
в коммитах не должно быть закомментированного кода

2021-11-16 06:12 UTC, c0dedbear commented on Homework3/myCV/myCV/Controller/HobbyViewController.swift
> +    //MARK: - Constants
можно и так сути не меняет, но у тебя во первых эти свойства торчат наружу так как не private, во вторых лучше смотрится все же внутри private enum

2021-11-16 06:12 UTC, c0dedbear commented on Homework3/myCV/myCV/Controller/HobbyViewController.swift
>      let titleLabel = UILabel()
зачем свойства открыты для других?

2021-11-16 08:26 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Utilites/TabBarControllerGenerator.swift
> +    static let instance = TabBarControllerGenerator()
Хотел сделать через Singleton ) Исправил.

2021-11-16 08:27 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Model/UserProfile.swift
> +    //static let instance = UserProfile()
Исправлено

2021-11-16 08:27 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Controller/HobbyViewController.swift
> +    //MARK: - Constants
Исправлено

2021-11-16 08:27 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Controller/HobbyViewController.swift
>      let titleLabel = UILabel()
Исправлено

2021-11-16 09:39 UTC, c0dedbear requested changes

2021-11-16 09:39 UTC, c0dedbear commented on Homework3/myCV/myCV/Controller/ExperienceViewController.swift
> +    private enum ExperienceViews {
вьюхи то не надо оборачивать! Речь шла про размеры и константы.

2021-11-16 10:07 UTC, svgnovosibirsk commented on Homework3/myCV/myCV/Controller/ExperienceViewController.swift
> +    private enum ExperienceViews {
Исправлено

2021-11-16 10:13 UTC, c0dedbear approved these changes
Принято

2021-11-16 10:13 UTC, merged