Реализовано ДЗ-4 Созданы CollctionView и еще два экрана. Реализованы …
svgnovosibirsk/FocusStartHomeworks pull request #4
Opened 2021-11-20 11:31 UTC by svgnovosibirsk

Приложение на основе Collection View

2021-11-21 15:06 UTC, c0dedbear requested changes
По приложению вроде все ок.

Забыл местами final у классов.
Магические цифры убрать в приватные enum с метриками/константами.
Не везде где надо есть private

2021-11-21 15:06 UTC, c0dedbear commented on Homework4/CollectionApp/CollectionApp/Model/SuperHero.swift
> +        heroArray.append(hero0)
зачем эти 10 строк кода и временная переменная, если можно просто вернуть сразу [hero0, hero1, ...]

2021-11-21 15:06 UTC, c0dedbear commented on Homework4/CollectionApp/CollectionApp/View/MyCollectionViewCell.swift
> +        //imageView.layer.cornerRadius = 5
Закомментированный код не допустим.

2021-11-22 03:37 UTC, svgnovosibirsk commented on Homework4/CollectionApp/CollectionApp/Model/SuperHero.swift
> +        heroArray.append(hero0)
Спасибо, исправил.

2021-11-22 03:37 UTC, svgnovosibirsk commented on Homework4/CollectionApp/CollectionApp/View/MyCollectionViewCell.swift
> +        //imageView.layer.cornerRadius = 5
Спасибо, исправил.

2021-11-22 16:44 UTC, c0dedbear approved these changes
Принято

2021-11-22 16:44 UTC, merged